# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lapze' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lapze
  pod 'Firebase'
  pod 'FirebaseAuth'
  pod 'FirebaseStorage'
  pod 'Firebase/Database'
  pod 'GoogleMaps'
  pod 'SnapKit'
  pod 'Charts'

end
